### PR TITLE
fix two more links to my site

### PR DESCRIPTION
**Pull request by compwiz32**
sorry for two pull requests.... :(

I found two more links that needed to be updated.

### CODE REVIEW

**Review by inafev — COMMENTED** [review]
A small typo within the new domain name in the 1st change

**Comment by compwiz32** [comment]
I am a dummy! i can't even spell my own domain name ... 

could you please correct as necessary? or I can resubmit... 

https://www.commandline.ninja

**Comment by inafev** [comment]
Sure! Will fix it later, I cannot edit it from my mobile app (GitHub for android), haha

**Comment by inafev** [comment]
Fixing the typo later by editing the merged file from a browser (GitHub for android can approve & merge PRs but cannot edit files).

**Pull request merged**
